## Arrays

In [1]:
import numpy as np

#### 1D Arrays

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([4,5,6])

In [3]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

#### 2D Arrays

In [7]:
a3 = np.array([[1,2,3],
             [4,5,6],
             [3,7,9]])

a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

#### 3D Arrays

In [9]:
a4 = np.array([[[10, 20], [30, 40]],
                 [[50, 50], [70, 80]],
                 [[90, 100], [110, 120]]])

a4.shape, a4.ndim, a4.dtype, a4.size, type(a4)

((3, 2, 2), 3, dtype('int32'), 12, numpy.ndarray)

#### Slicing

In [19]:
a5 = np.array([1, 2, 3, 4, 5])
print(a5[0])
print(a5[:3])


1
[1 2 3]


In [20]:
a6 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

a6.shape
a7 = a6[:2, :]
print(a7)

[[1 2 3]
 [4 5 6]]


In [23]:
a7 = a6[:3, :2]
print(a7)

[[1 2]
 [4 5]
 [7 8]]


In [26]:
a8 = np.array([[[10, 20], [30, 40]],
                 [[50, 50], [70, 80]],
                 [[90, 100], [110, 120]]])

a9 = a8[1:, :, :]
print(a9)

[[[ 50  50]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]


In [28]:
a8[1,1,:]

array([70, 80])

In [30]:
a8[0, 1, 1]

40

In [31]:
a8[2, 0, 0]

90

In [39]:
a7 = np.array ([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [10,20,30,40,50,60],
              [50,60,70,80,90,100],
              [30,31,32,33,34,35]])

sel_rows = [0,2,4]
sel_columns = [1,3,4]
a7[sel_rows, :]


array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [30, 31, 32, 33, 34, 35]])

In [50]:
a7[[0,2,4], 1::2]

array([[ 2,  4,  6],
       [20, 40, 60],
       [31, 33, 35]])

In [25]:
a7 = np.array ([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [10,20,30,40,50,60],
              [50,60,70,80,90,100],
              [30,31,32,33,34,35]])
# print(a7.ndim)
sel_rows = [0,2,4]
sel_columns = [1,3,4,5]
a7[np.ix_(sel_rows, sel_columns)]
# a7[sel_rows, sel_columns]


2


array([[ 2,  4,  5,  6],
       [20, 40, 50, 60],
       [31, 33, 34, 35]])

In [60]:
a8 = np.random.randint(10, size=(3,4,5))
a8


array([[[9, 4, 8, 3, 1],
        [0, 3, 5, 3, 9],
        [4, 0, 6, 9, 4],
        [1, 0, 2, 9, 9]],

       [[8, 7, 5, 1, 7],
        [4, 0, 5, 9, 1],
        [5, 7, 7, 0, 1],
        [6, 9, 7, 1, 2]],

       [[9, 8, 0, 2, 7],
        [2, 8, 5, 7, 3],
        [1, 3, 3, 6, 3],
        [3, 1, 0, 6, 3]]])

In [64]:
a8[:,:,:4]

array([[[9, 4, 8, 3],
        [0, 3, 5, 3],
        [4, 0, 6, 9],
        [1, 0, 2, 9]],

       [[8, 7, 5, 1],
        [4, 0, 5, 9],
        [5, 7, 7, 0],
        [6, 9, 7, 1]],

       [[9, 8, 0, 2],
        [2, 8, 5, 7],
        [1, 3, 3, 6],
        [3, 1, 0, 6]]])

In [21]:
np.random.seed(0)
r1 = np.random.randint(10, size=(3,4,5))
r2 = np.random.random((4,5))
r3 = np.random.rand(4,5)

print('r1')
print(r1)
print('r2')
print(r2)
print('r3')
print(r3)

r0
[0 1 2 3 4 5 6 7 8 9]
r1
[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]
r2
[[0.44994999 0.61306346 0.90234858 0.09928035 0.96980907]
 [0.65314004 0.17090959 0.35815217 0.75068614 0.60783067]
 [0.32504723 0.03842543 0.63427406 0.95894927 0.65279032]
 [0.63505887 0.99529957 0.58185033 0.41436859 0.4746975 ]]
r3
[[0.6235101  0.33800761 0.67475232 0.31720174 0.77834548]
 [0.94957105 0.66252687 0.01357164 0.6228461  0.67365963]
 [0.971945   0.87819347 0.50962438 0.05571469 0.45115921]
 [0.01998767 0.44171092 0.97958673 0.35944446 0.48089353]]
r4
9


In [23]:
r0 = np.arange(10)
r4 = np.random.choice(r0)
print('r0')
print(r0)
print('r4')
print(r4)

r0
[0 1 2 3 4 5 6 7 8 9]
r4
3


In [14]:
np.random.seed(10)
r2 = np.random.random((4,5))
r2

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [81]:
np.random.seed(10)
r3 = np.random.random((4,5))
r3

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [90]:
r4 = np.arange(100)

In [91]:
r4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [106]:
r5 = np.arange(10,50)
r5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [107]:
r5 = np.arange(10,50,2)
r5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [108]:
r6 = np.ones((5,3))
r6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
r6 = np.ones((5,3))*2
r6

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [97]:
type(r6)

numpy.ndarray

In [98]:
r6.dtype

dtype('float64')

In [101]:
r5 = r6.astype(int)
r5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [103]:
r6 = np.zeros((2,3))
r6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
b1 = np.array([1,2,3,4,5])
b2 = np.ones((5,))
print(b1)
print(b2)

result1 = b1 + b2
result2 = b1 - b2
result3 = b1 / b2
result4 = b1 * b2
print(result1)
print(result2)
print(result3)
print(result4)

[1 2 3 4 5]
[1. 1. 1. 1. 1.]
[2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4.]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [124]:
ones = np.ones((5,))*2
b3 = np.array([[10,20,30,40,50],
              [6,7,8,9,10]])
print(b3)
print(ones)


result1 = b3 + ones
result2 = b3 - ones
result3 = b3 / ones
result4 = b3 * ones
print(result1)
print(result2)
print(result3)
print(result4)

[[10 20 30 40 50]
 [ 6  7  8  9 10]]
[2. 2. 2. 2. 2.]
[[12. 22. 32. 42. 52.]
 [ 8.  9. 10. 11. 12.]]
[[ 8. 18. 28. 38. 48.]
 [ 4.  5.  6.  7.  8.]]
[[ 5.  10.  15.  20.  25. ]
 [ 3.   3.5  4.   4.5  5. ]]
[[ 20.  40.  60.  80. 100.]
 [ 12.  14.  16.  18.  20.]]


In [133]:
np.random.seed(0)
ar1 = np.random.randint(10, size = (2,2))
np.random.seed(0)
ar2 = np.random.randint(10, size = (2,2))
print(ar1)
print(ar2)

res1 = np.dot(ar1, ar2)
res2 = ar1@ar2
print(res1)
print(res2)

[[5 0]
 [3 3]]
[[5 0]
 [3 3]]
[[25  0]
 [24  9]]
[[25  0]
 [24  9]]


In [135]:
np_array = np.array([10,20,30,40])
temp = np_array
temp[0]
temp.dtype

dtype('int32')

In [136]:
v1 = np_array.view()
print(v1)

[10 20 30 40]


In [137]:
v1.dtype

dtype('int32')

In [138]:
v2 = np_array.copy()
print(v2)

[10 20 30 40]


In [139]:
v1[0] = 100
print(np_array)

[100  20  30  40]


In [140]:
v2[0] = 40
print(np_array)

[100  20  30  40]


In [141]:
temp[0] = 50
print(np_array)

[50 20 30 40]


#### Reshaping an Array

In [151]:
arr = np.arange(24)
print(arr)

arr1 = arr.reshape(4,6)
print('\n Reshaped to 4,6')
print(arr1)

arr2 = arr.reshape(3,4,2)
print('\n Reshaped to 3,4,2')
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 Reshaped to 4,6
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 Reshaped to 3,4,2
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [153]:
arr1 = np.random.randint(10, size = (3,4))
print(arr1)

arr2 = arr1.reshape(3,2,2)
print(arr2)

[[7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
[[[7 9]
  [3 5]]

 [[2 4]
  [7 6]]

 [[8 8]
  [1 6]]]


In [160]:
arr1 = np.random.randint(10, size = (4,3,3))
print(arr1)

arr2 = arr1.reshape(-1)
print(arr2)

[[[0 1 5]
  [9 3 0]
  [5 0 1]]

 [[2 4 2]
  [0 3 2]
  [0 7 5]]

 [[9 0 2]
  [7 2 9]
  [2 3 3]]

 [[2 3 4]
  [1 2 9]
  [1 4 6]]]
[0 1 5 9 3 0 5 0 1 2 4 2 0 3 2 0 7 5 9 0 2 7 2 9 2 3 3 2 3 4 1 2 9 1 4 6]


In [161]:
arr3 = arr1.flatten()
print(arr3)

[0 1 5 9 3 0 5 0 1 2 4 2 0 3 2 0 7 5 9 0 2 7 2 9 2 3 3 2 3 4 1 2 9 1 4 6]


In [162]:
arr1

array([[[0, 1, 5],
        [9, 3, 0],
        [5, 0, 1]],

       [[2, 4, 2],
        [0, 3, 2],
        [0, 7, 5]],

       [[9, 0, 2],
        [7, 2, 9],
        [2, 3, 3]],

       [[2, 3, 4],
        [1, 2, 9],
        [1, 4, 6]]])

In [163]:
arr2

array([0, 1, 5, 9, 3, 0, 5, 0, 1, 2, 4, 2, 0, 3, 2, 0, 7, 5, 9, 0, 2, 7,
       2, 9, 2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6])

In [164]:
arr3

array([0, 1, 5, 9, 3, 0, 5, 0, 1, 2, 4, 2, 0, 3, 2, 0, 7, 5, 9, 0, 2, 7,
       2, 9, 2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6])

In [165]:
arr3[0]=100

In [166]:
arr3

array([100,   1,   5,   9,   3,   0,   5,   0,   1,   2,   4,   2,   0,
         3,   2,   0,   7,   5,   9,   0,   2,   7,   2,   9,   2,   3,
         3,   2,   3,   4,   1,   2,   9,   1,   4,   6])

In [167]:
arr1

array([[[0, 1, 5],
        [9, 3, 0],
        [5, 0, 1]],

       [[2, 4, 2],
        [0, 3, 2],
        [0, 7, 5]],

       [[9, 0, 2],
        [7, 2, 9],
        [2, 3, 3]],

       [[2, 3, 4],
        [1, 2, 9],
        [1, 4, 6]]])

In [173]:
b1 = np.random.randint(10, size=(3,3))
print(b1)
bt = b1.transpose()
print(bt)

[[3 6 9]
 [8 0 8]
 [5 9 0]]
[[3 8 5]
 [6 0 9]
 [9 8 0]]


In [174]:
b1 = np.random.randint(10, size=(3,3))
print(b1)
bt = b1.T
print(bt)

[[9 6 5]
 [3 1 8]
 [0 4 9]]
[[9 3 0]
 [6 1 4]
 [5 8 9]]


In [3]:
arr = np.array([4,23,12,1,3,4,2,10])
arr_sorted = np.sort(arr)
arr_sorted

array([ 1,  2,  3,  4,  4, 10, 12, 23])

In [5]:
arr2d = np.array([[3, 2, 1], [6, 5, 4]])
arr_sorted = np.sort(arr2d)
arr_sorted

array([[1, 2, 3],
       [4, 5, 6]])

#### More methods

#### Linspace:
#### This function generates evenly spaced numbers over a specified range. It is particularly useful for plotting, numerical analysis, and simulations where you need a sequence of values within a given interval.

In [3]:
arr1 = np.linspace(0,2,9)

In [4]:
arr1

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [5]:
arr2 = np.linspace(0,10,5)
arr2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
# By setting endpoint=False, the function does not include the stop value
arr3 = np.linspace(0, 10, 5, endpoint=False)
print(arr3)

[0. 2. 4. 6. 8.]


In [7]:
# By setting retstep=True, numpy.linspace() returns both the array and the spacing (step).
arr4, step = np.linspace(1, 5, 5, retstep=True)
print("Array:", arr4)
print("Step:", step)

Array: [1. 2. 3. 4. 5.]
Step: 1.0


#### Creating an identity matrix

In [8]:
arr1 = np.eye(2)
arr1

array([[1., 0.],
       [0., 1.]])

In [9]:
arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])