In [2]:
import numpy as np

## Easy

#### 1. Create a 1D array of 20 sequential integers and reshape it into a 4x5 matrix

In [6]:
arr = np.arange(20)
print('The original array is')
print(arr)
reshaped_array = arr.reshape(4,5)
print('The reshaped array is')
print(reshaped_array)

The original array is
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The reshaped array is
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


#### 2. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

In [11]:
arr = np.arange(22, 71, 2)
print(arr)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


#### 3. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

In [13]:
arr = np.arange(21, 72, 2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


#### 4. Generate an array of 15 random integers and sort it in ascending order.

In [19]:
arr = np.random.randint(100, size = (15))
sorted_array = np.sort(arr)
print('The random unsorted array is: ')
print(arr)
print('The sorted array is: ')
print(sorted_array)

The random unsorted array is: 
[74 58 14 17 42  9 62  6 40  6 80 91 90 79 48]
The sorted array is: 
[ 6  6  9 14 17 40 42 48 58 62 74 79 80 90 91]


#### 5. Create a 1D array of zeros of length 10 and set the 5th element to 1.

In [33]:
# arr = np.zeros((1,10))
# print(f'The original array: {arr}')
# arr[0,4] = 1
# print(f'The updated array: {arr}')

arr = np.zeros((10,))
print(f'The original array: {arr}')

arr[4] = 1
print(f'The updated array: {arr}')

The original array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The updated array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Find the unique elements in a given array [1, 2, 2, 3, 4, 4, 5].

In [31]:
arr = np.array([1,2,2,3,4,4,5])
arr1 = np.unique(arr)
print(arr1)

[1 2 3 4 5]


#### 7. Create an array with values ranging from 0 to 10 and reverse the array.

In [36]:
arr = np.arange(11)
print(arr)
arr_reversed = arr[::-1]
print(arr_reversed)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


#### 8. Given a list of birds and their corresponding age, calculate:
#### a. the mean age of the Crane bird (rounded off to 2 decimal points)
#### b. find the name of the oldest bird in the list
#### birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
#### age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [59]:
birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

crane_ages = [age[i] for i in range(len(birds)) if birds[i] == 'Cranes']
mean_crane_age = round(np.mean(crane_ages), 2)

max_age = max(age)
oldest_bird = birds[age.index(max_age)] 

print(f"Mean age of Cranes: {mean_crane_age}")
print(f"Oldest bird: {oldest_bird}")

Mean age of Cranes: 4.75
Oldest bird: plovers


#### 9. Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:
#### a. the second to the fourth row of the original array,
#### b. the elements in these rows should be from the last three columns of the corresponding rows of the original array,
#### c. the rows should be in reversed order.

In [47]:
np.random.seed(0)
arr = np.random.randint(10, size=(5,5))
print('The original array is')
print(arr)

# rows = [1, 2, 3]
# columns = [2, 3, 4]

new_arr = arr[1:4, 2:5][::-1]
print('The subarray is')
print(new_arr)

The original array is
[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
The subarray is
[[7 8 1]
 [8 8 1]
 [5 2 4]]


## Moderate

#### 1. Create a 4x4 matrix and replace all elements on its diagonal with 7.

In [62]:
matrix = np.eye(4) * 7
print(matrix)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


#### 2. Given two arrays of the same size, compute their element-wise product.

In [65]:
np.random.seed(0)
arr1 = np.random.randint(10, size=(4,4))
arr2 = np.random.randint(10, size=(4,4))
print('Array 1:')
print(arr1)
print('Array 2: ')
print(arr2)

result = arr1 * arr2
print('Result: ')
print(result)

Array 1:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Array 2: 
[[7 7 8 1]
 [5 9 8 9]
 [4 3 0 3]
 [5 0 2 3]]
Result: 
[[35  0 24  3]
 [35 81 24 45]
 [ 8 12  0 18]
 [40  0  2 18]]


#### 3. Create a random 6x6 matrix and compute the mean and standard deviation of its elements.

In [71]:
arr = np.random.randint(10, size=(6,6))
print(arr)
mean = round(np.mean(arr), 2)
standard_deviation = round(np.std(arr), 2)
print(f'The mean is: {mean}')
print(f'The standard deviation is: {standard_deviation}')

[[7 3 2 3 9 7]
 [7 5 1 2 2 8]
 [1 5 8 4 0 2]
 [5 5 0 8 1 1]
 [0 3 8 8 4 4]
 [0 9 3 7 3 2]]
The mean is: 4.08
The standard deviation is: 2.86


#### 4. Stack two arrays vertically and horizontally (use vstack and hstack).

In [5]:
array1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9], 
                   [10, 11, 12]])

vertical_stack = np.vstack((array1, array2))
print("Vertically Stacked Array:")
print(vertical_stack)

horizontal_stack = np.hstack((array1, array2))
print("\nHorizontally Stacked Array:")
print(horizontal_stack)

Vertically Stacked Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontally Stacked Array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### 5. Create a 1D array of 50 random floats between 0 and 1, and count how many values are greater than 0.5.

In [74]:
arr = np.random.rand(50)
print(arr)
i = 0
for item in arr:
    if (item > 0.5):
        i = i + 1
print(f'The number of values that are greater than 0.5 are: {i}')

[0.47837031 0.49739137 0.63947252 0.36858461 0.13690027 0.82211773
 0.18984791 0.51131898 0.22431703 0.09784448 0.86219152 0.97291949
 0.96083466 0.9065555  0.77404733 0.33314515 0.08110139 0.40724117
 0.23223414 0.13248763 0.05342718 0.72559436 0.01142746 0.77058075
 0.14694665 0.07952208 0.08960303 0.67204781 0.24536721 0.42053947
 0.55736879 0.86055117 0.72704426 0.27032791 0.1314828  0.05537432
 0.30159863 0.26211815 0.45614057 0.68328134 0.69562545 0.28351885
 0.37992696 0.18115096 0.78854551 0.05684808 0.69699724 0.7786954
 0.77740756 0.25942256]
The number of values that are greater than 0.5 are: 20


In [3]:
arr = np.random.rand(50)

count_greater_than_0_5 = np.sum(arr > 0.5)

print("Generated array:", arr)
print("Count of values greater than 0.5:", count_greater_than_0_5)

Generated array: [0.84485144 0.66580547 0.29118359 0.97822482 0.71888628 0.17034724
 0.63049945 0.27170146 0.41936848 0.78237783 0.02174618 0.54204765
 0.39741217 0.06102406 0.05642048 0.06423656 0.34051123 0.58984481
 0.26018263 0.43246453 0.95966014 0.77025557 0.89236536 0.85872499
 0.22874068 0.40114226 0.13725182 0.8037386  0.4138904  0.57258027
 0.34414692 0.23639341 0.04917986 0.89078377 0.83932884 0.80610593
 0.01496353 0.56855117 0.20239793 0.43157811 0.44882887 0.32334232
 0.58686276 0.66796798 0.79574371 0.20648346 0.12561881 0.20760092
 0.62802011 0.77293467]
Count of values greater than 0.5: 23


#### 6. Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)
#### birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
#### age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [1]:
birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers',
         'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

sorted_indices = sorted(range(len(age)), key=lambda i: age[i])
sorted_birds = [birds[i] for i in sorted_indices]

print(sorted_birds)

['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']


#### 7. Given the shape of an array and a range, Return an array of specified shape, consisting of random integers from "discrete uniform" distribution, in given range [low, high].
#### Note: high is inclusive in range.
####  Input Format:
#### o Input has two lines.
#### o First line contains the shape of the array.
#### o Second line contains the range (low, high).
####  Output Format: A NumPy array

In [6]:
shape = tuple(map(int, input("Enter shape of the array: ").split()))

low, high = map(int, input("Enter range (low high): ").split())

random_array = np.random.randint(low, high + 1, size=shape)

print(random_array)

Enter shape of the array:  4 4
Enter range (low high):  10 20


[[10 11 19 20]
 [17 12 18 14]
 [15 15 10 10]
 [17 17 10 10]]


## Challenging

#### 1. Create a 10x10 matrix with random integers and find the indices of the top 3 maximum values.
#### o Concepts: Matrix generation, indexing with conditions.

In [59]:
np.random.seed(0)
arr = np.random.randint(100, size = (10,10))
print(arr)
flattened_arr = arr.flatten()

sorted_arr = np.sort(flattened_arr)

top_3 = np.partition(sorted_arr, -3)[-3:]

indices_of_top3 = np.argwhere(np.isin(arr, top_3))

formatted_indices = [f"({x},{y})" for x, y in indices_of_top3]

print("Indices of Top 3 Values:", ", ".join(formatted_indices))

[[44 47 64 67 67  9 83 21 36 87]
 [70 88 88 12 58 65 39 87 46 88]
 [81 37 25 77 72  9 20 80 69 79]
 [47 64 82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74 23 35]
 [75 55 28 34  0  0 36 53  5 38]
 [17 79  4 42 58 31  1 65 41 57]
 [35 11 46 82 91  0 14 99 53 12]
 [42 84 75 68  6 68 47  3 76 52]
 [78 15 20 99 58 23 79 13 85 48]]
Indices of Top 3 Values: (3,3), (7,7), (9,3)


#### 2. Solve a system of three linear equations using NumPy’s linalg.solve() function.
#### o Concepts: Linear algebra, system of equations.

In [35]:
# Coefficients
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Constants
B = np.array([8, -11, -3])

X = np.linalg.solve(A, B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  3. -1.]


#### 3. Generate a random 8x8 matrix and compute its eigenvalues and eigenvectors.
#### o Concepts: Linear algebra, eigenvalues/eigenvectors.

In [55]:
np.random.seed(0)
matrix = np.random.randint(10, size = (8,8))

print(matrix)
w,v = np.linalg.eig(matrix)

print('The eigenvalues are')
print(w)
print('THe eigenvectors are')
print(v)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]
 [2 0 0 4 5 5 6 8]
 [4 1 4 9 8 1 1 7]]
The eigenvalues are
[34.33543955+0.j         -8.85560035+0.j          6.48382308+2.02005973j
  6.48382308-2.02005973j  1.17287558+5.76617251j  1.17287558-5.76617251j
 -3.11874117+0.j          1.32550464+0.j        ]
THe eigenvectors are
[[ 0.33081297+0.j          0.37358978+0.j         -0.15259071+0.0986812j
  -0.15259071-0.0986812j   0.21398001+0.07027595j  0.21398001-0.07027595j
   0.10753755+0.j          0.21815126+0.j        ]
 [ 0.42273382+0.j          0.42446663+0.j          0.24243757-0.4015283j
   0.24243757+0.4015283j  -0.14834741-0.06988714j -0.14834741+0.06988714j
  -0.00084266+0.j         -0.3271723 +0.j        ]
 [ 0.56424955+0.j         -0.12427948+0.j          0.54616493+0.j
   0.54616493-0.j          0.51515587+0.j          0.51515587-0.j
  -0.02501831+0.j          0.23310923+0.j        ]
 [ 0.16920564+0.j         -0.36

#### 4. Create a large random matrix (1000x1000) and find the time taken to compute the sum of its elements.
#### o Concepts: Performance evaluation, time computation.

In [53]:
import time
np.random.seed(0)
matrix = np.random.randint(10, size = (1000, 1000))

start_time = time.time()
print(start_time)

sum_of_matrix = np.sum(matrix)

end_time = time.time()
print(end_time)

time_taken = end_time - start_time

print(f'Time taken is: {time_taken}')

1739789159.7216017
1739789159.7226038
Time taken is: 0.0010020732879638672


In [54]:
A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

rows_A, cols_A = A.shape
rows_B, cols_B = B.shape

manual_result = np.zeros((rows_A, cols_B))

start_time_manual = time.time()
for i in range(rows_A):
    for j in range(cols_B):
        manual_result[i][j] = 0 
        for k in range(cols_A):
            manual_result[i][j] += A[i][k] * B[k][j] 
end_time_manual = time.time()
manual_time = end_time_manual - start_time_manual

start_time_numpy = time.time()
numpy_result = np.dot(A, B)
end_time_numpy = time.time()
numpy_time = end_time_numpy - start_time_numpy

print(f"Time taken by manual multiplication: {manual_time} seconds")
print(f"Time taken by NumPy's dot product: {numpy_time} seconds")


Time taken by manual multiplication: 168.40191769599915 seconds
Time taken by NumPy's dot product: 0.46849846839904785 seconds
